Repository boostcampwm-2021/android04-God-Fisherman, pull requests merged in 2021-11, with the labels that each got.

#52 Camera 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraViewModel.kt
  app/src/main/res/drawable/bg_primary_to_secondary_circle.xml
  app/src/main/res/drawable/img_fish_guide.png
  app/src/main/res/drawable/img_line_guide.xml
  app/src/main/res/drawable/img_money_guide.xml
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 📸사진 업로드 화면

#53 수평계 구현
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraActivity.kt
  app/src/main/java/com/android04/godfisherman/utils/LevelView.kt
  app/src/main/res/layout/activity_camera.xml
Labels: 📸사진 업로드 화면

#56 뷰바인딩 제거 및 파이어베이스 설정
  app/build.gradle
  app/google-services.json
  app/src/main/java/com/android04/godfisherman/ui/base/BaseActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/dashboard/DashboardFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/notifications/NotificationsFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchInfoFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notifications.xml
  build.gradle
Labels: 📸사진 업로드 화면

#57 업로드 화면 레이아웃 디자인
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadViewModel.kt
  app/src/main/res/drawable/bg_gradient_surface_to_white.xml
  app/src/main/res/drawable/ic_arrow_back_round.xml
  app/src/main/res/drawable/ic_fish_type.xml
  app/src/main/res/drawable/ic_length.xml
  app/src/main/res/drawable/ic_location_outline.xml
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/layout/item_fish_type.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 📸사진 업로드 화면

#54 카메라 물체 인식 기능 추가
  app/build.gradle
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraActivity.kt
  app/src/main/java/com/android04/godfisherman/utils/Extension.kt
  app/src/main/java/com/android04/godfisherman/utils/ObjectDetector.kt
  app/src/main/res/drawable/bg_primary_radius_5dp.xml
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: 📸사진 업로드 화면

#55 현재 위치 정보 요청 및 저장
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android04/godfisherman/data/datasource/remote/LocationRemoteDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/remote/LocationRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/LocationRepository.kt
  app/src/main/java/com/android04/godfisherman/di/LocationDataSourceDiModule.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainActivity.kt
  app/src/main/java/com/android04/godfisherman/utils/AddressHelper.kt
  app/src/main/java/com/android04/godfisherman/utils/LocationHelper.kt
  app/src/main/java/com/android04/godfisherman/utils/PermissionCheck.kt
  app/src/main/java/com/android04/godfisherman/utils/SharedPreferenceManager.kt
  app/src/main/res/layout/fragment_home.xml
Labels: 🎪홈 화면

#60 위치 정보 가져오기 수정
  app/src/main/java/com/android04/godfisherman/data/datasource/remote/LocationRemoteDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/remote/LocationRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/LocationRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/utils/AddressHelper.kt
  app/src/main/java/com/android04/godfisherman/utils/LocationHelper.kt
  app/src/main/res/layout/fragment_home.xml
Labels: 🎪홈 화면

#59 Upload - 어종 리스트 동적 추가
  app/build.gradle
  app/src/main/java/com/android04/godfisherman/data/datasource/uploadDataSource/UploadDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/uploadDataSource/local/UploadLocalDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/uploadDataSource/remote/UploadRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/UploadRepository.kt
  app/src/main/java/com/android04/godfisherman/di/UploadDiModule.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadViewModel.kt
  app/src/main/res/layout/activity_upload.xml
Labels: 📸사진 업로드 화면

#63 카메라 바운딩 박스 수정, 체장 계산 기능 추가
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadActivity.kt
  app/src/main/java/com/android04/godfisherman/utils/BindingAdapter.kt
  app/src/main/java/com/android04/godfisherman/utils/Const.kt
  app/src/main/java/com/android04/godfisherman/utils/ToastFactory.kt
  app/src/main/java/com/android04/godfisherman/utils/Util.kt
  app/src/main/res/drawable/bg_fish_yellow_stroke_5dp.xml
  app/src/main/res/drawable/bg_money_red_stroke_5dp.xml
  app/src/main/res/drawable/bg_primary_to_secondary_circle.xml
  app/src/main/res/drawable/ic_baseline_file_upload_24.xml
  app/src/main/res/drawable/img_fish_guide.png
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 📸사진 업로드 화면

#65 Design: 스톱워치 화면 UI
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/res/drawable/bg_circle_stopwatch.xml
  app/src/main/res/drawable/bg_gradient_main.xml
  app/src/main/res/drawable/btn_start.xml
  app/src/main/res/drawable/btn_start_to_stop.xml
  app/src/main/res/drawable/btn_stop.xml
  app/src/main/res/drawable/ic_baseline_location_on_16.xml
  app/src/main/res/drawable/test_fish_img.png
  app/src/main/res/layout/activity_stopwatch.xml
  app/src/main/res/layout/item_time_line_in_stop_watch.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: ⏱낚시 스톱워치 화면

#64 Firebase의 Storage, Firestore에 낚시 기록 업로드
  app/build.gradle
  app/src/main/java/com/android04/godfisherman/data/datasource/uploadDataSource/UploadDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/uploadDataSource/remote/UploadRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/entity/FishingRecord.kt
  app/src/main/java/com/android04/godfisherman/data/entity/Type.kt
  app/src/main/java/com/android04/godfisherman/data/repository/UploadRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadViewModel.kt
  app/src/main/java/com/android04/godfisherman/utils/BindingAdapter.kt
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/menu/menu_upload_top_app_bar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 📸사진 업로드 화면

#66 스톱워치화면 타임라인 리사이클러뷰 표시
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android04/godfisherman/common/App.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchActivity2.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/TimeLineDataTest.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/TimelineListAdapter.kt
  app/src/main/java/com/android04/godfisherman/utils/RecyclerViewEmptySupport.kt
  app/src/main/res/layout/activity_stopwatch.xml
  app/src/main/res/layout/activity_stopwatch2.xml
  app/src/main/res/layout/item_time_line_in_stop_watch.xml
  app/src/main/res/values/strings.xml
Labels: ⏱낚시 스톱워치 화면

#70 스톱워치 및 포그라운드 서비스 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/lottie_stopwatch_info_fishing.json
  app/src/main/java/com/android04/godfisherman/ui/main/MainActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/notifications/NotificationsViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchInfoFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchInfoViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchViewModel.kt
  app/src/main/java/com/android04/godfisherman/utils/BindingAdapter.kt
  app/src/main/java/com/android04/godfisherman/utils/Extension.kt
  app/src/main/java/com/android04/godfisherman/utils/StopwatchNotification.kt
  app/src/main/java/com/android04/godfisherman/utils/StopwatchService.kt
  app/src/main/res/drawable/bg_gradient_surface_to_secondary.xml
  app/src/main/res/drawable/bg_stopwatch_info_start_fishing.xml
  app/src/main/res/drawable/ic_baseline_stop_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_stopwatch.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notifications.xml
  app/src/main/res/layout/fragment_stopwatch_info.xml
  app/src/main/res/values/strings.xml
Labels: 스톱워치 안내 화면, ⏱낚시 스톱워치 화면

#73 지오코더를 네이버 Reverse Geocoder API로 변경
  app/build.gradle
  app/src/main/java/com/android04/godfisherman/data/datasource/remote/LocationRemoteDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/remote/LocationRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/LocationRepository.kt
  app/src/main/java/com/android04/godfisherman/network/NaverApi.kt
  app/src/main/java/com/android04/godfisherman/network/RetrofitClient.kt
  app/src/main/java/com/android04/godfisherman/network/response/RegionResponse.kt
  app/src/main/java/com/android04/godfisherman/ui/base/BaseFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/utils/AddressHelper.kt
  build.gradle
Labels: 🎪홈 화면

#74 스톱워치 동작 중 임시 타임라인 피드 정보를 로컬 데이터베이스에 저장하기 위한 세팅
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android04/godfisherman/data/datasource/stopwatchdatasource/StopwatchDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/stopwatchdatasource/local/StopwatchLocalDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/StopwatchRepository.kt
  app/src/main/java/com/android04/godfisherman/di/LocalDatabaseDiModule.kt
  app/src/main/java/com/android04/godfisherman/di/StopwatchDiModule.kt
  app/src/main/java/com/android04/godfisherman/localdatabase/DatabaseTypeConverter.kt
  app/src/main/java/com/android04/godfisherman/localdatabase/LocalDatabase.kt
  app/src/main/java/com/android04/godfisherman/localdatabase/dao/TemporaryFishingRecordDao.kt
  app/src/main/java/com/android04/godfisherman/localdatabase/entity/TemporaryFishingRecord.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopWatchInfoTestViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchActivity2.kt
Labels: 📸사진 업로드 화면, ⏱낚시 스톱워치 화면

#72 Feed UI 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android04/godfisherman/data/entity/FishingRecord.kt
  app/src/main/java/com/android04/godfisherman/data/entity/Type.kt
  app/src/main/java/com/android04/godfisherman/data/repository/UploadRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/dashboard/DashboardFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/dashboard/DashboardViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedData.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedRecyclerViewAdapter.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/TimelineRecyclerViewAdapter.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/TimelineViewPagerAdapter.kt
  app/src/main/java/com/android04/godfisherman/utils/BindingAdapter.kt
  app/src/main/res/drawable/bg_image_error.xml
  app/src/main/res/drawable/bg_loading_skeleton.xml
  app/src/main/res/drawable/ic_baseline_arrow_drop_down_primary.xml
  app/src/main/res/drawable/ic_baseline_arrow_drop_up_primary.xml
  app/src/main/res/drawable/ic_clarity_fish_line.xml
  app/src/main/res/drawable/ic_feed_location.xml
  app/src/main/res/drawable/ic_line_down.xml
  app/src/main/res/drawable/ic_line_up.xml
  app/src/main/res/drawable/ic_timeline_fish_icon.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed_photo_type.xml
  app/src/main/res/layout/item_feed_timeline_type.xml
  app/src/main/res/layout/item_timeline.xml
  app/src/main/res/layout/item_timeline_photo.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 피드 화면

#79 피드 데이터 요청 및 표시
  app/src/main/java/com/android04/godfisherman/data/DTO/FeedDTO.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/FeedDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/local/FeedLocalDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/remote/FeedRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/entity/FishingRecord.kt
  app/src/main/java/com/android04/godfisherman/data/entity/Type.kt
  app/src/main/java/com/android04/godfisherman/data/repository/FeedRepository.kt
  app/src/main/java/com/android04/godfisherman/di/FeedDiModule.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedViewModel.kt
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: 피드 화면

#81 스톱워치 오류 수정
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchInfoFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchViewModel.kt
  app/src/main/java/com/android04/godfisherman/utils/StopwatchService.kt
Labels: 스톱워치 안내 화면, ⏱낚시 스톱워치 화면

#82 피드 필터링
  app/src/main/assets/lottie_loading.json
  app/src/main/java/com/android04/godfisherman/common/Type.kt
  app/src/main/java/com/android04/godfisherman/data/DTO/FeedDTO.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/FeedDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/remote/FeedRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/uploadDataSource/UploadDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/uploadDataSource/remote/UploadRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/entity/TypeInfo.kt
  app/src/main/java/com/android04/godfisherman/data/repository/FeedRepository.kt
  app/src/main/java/com/android04/godfisherman/data/repository/StopwatchRepository.kt
  app/src/main/java/com/android04/godfisherman/data/repository/UploadRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedRecyclerViewAdapter.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedViewModel.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed_photo_type.xml
  app/src/main/res/layout/item_feed_timeline_type.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: 피드 화면

#84 홈 UI 수정, 유튜브 영상 표시, 기타 수정
  app/src/main/java/com/android04/godfisherman/common/App.kt
  app/src/main/java/com/android04/godfisherman/common/NetworkChecker.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/homedatasource/HomeDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/homedatasource/remote/HomeRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/HomeRepository.kt
  app/src/main/java/com/android04/godfisherman/di/HomeDiModule.kt
  app/src/main/java/com/android04/godfisherman/network/RetrofitClient.kt
  app/src/main/java/com/android04/godfisherman/network/YoutubeApi.kt
  app/src/main/java/com/android04/godfisherman/network/response/YoutubeResponse.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeRecommendData.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/home/RecommendRecyclerViewAdapter.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchActivity.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_recommend.xml
  app/src/main/res/values/strings.xml
Labels: 🎪홈 화면

#85 피드 디자인 일부 수정, 앱 아이콘 및 이름 변경
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher_god_fisherman-playstore.png
  app/src/main/java/com/android04/godfisherman/data/repository/FeedRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedRecyclerViewAdapter.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed_photo_type.xml
  app/src/main/res/layout/item_feed_timeline_type.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_god_fisherman.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_god_fisherman_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_god_fisherman.png
  app/src/main/res/mipmap-hdpi/ic_launcher_god_fisherman_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_god_fisherman_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_god_fisherman.png
  app/src/main/res/mipmap-mdpi/ic_launcher_god_fisherman_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_god_fisherman_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_god_fisherman.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_god_fisherman_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_god_fisherman_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_god_fisherman.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_god_fisherman_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_god_fisherman_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_god_fisherman.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_god_fisherman_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_god_fisherman_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/ic_launcher_god_fisherman_background.xml
  app/src/main/res/values/strings.xml
Labels: 🐟피드 화면

#83 스톱워치 화면 모션 레이아웃 설정
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchInfoFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/TestStopwatchFragment.kt
  app/src/main/java/com/android04/godfisherman/utils/BindingAdapter.kt
  app/src/main/res/drawable/ic_close_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_stopwatch_info.xml
  app/src/main/res/layout/fragment_test_stopwatch.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/xml/activity_main_xml_container_scene.xml
Labels: ⏱낚시 스톱워치 화면

#87 피드 데이터 캐싱, 일부 버그 수정
  app/build.gradle
  app/src/main/java/com/android04/godfisherman/common/NetworkChecker.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/FeedDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/local/FeedLocalDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/remote/FeedRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/FeedRepository.kt
  app/src/main/java/com/android04/godfisherman/di/AppDiModule.kt
  app/src/main/java/com/android04/godfisherman/di/LocalDatabaseDiModule.kt
  app/src/main/java/com/android04/godfisherman/localdatabase/LocalDatabase.kt
  app/src/main/java/com/android04/godfisherman/localdatabase/dao/FeedCachedDao.kt
  app/src/main/java/com/android04/godfisherman/localdatabase/entity/FeedCached.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedRecyclerViewAdapter.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainViewModel.kt
  app/src/main/java/com/android04/godfisherman/utils/FeedUtil.kt
  app/src/main/java/com/android04/godfisherman/utils/LocationHelper.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed_timeline_type.xml
Labels: 🐟피드 화면

#94 피드, 업로드 디테일 처리
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/FeedDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/local/FeedLocalDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/remote/FeedRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/FeedRepository.kt
  app/src/main/java/com/android04/godfisherman/data/repository/StopwatchRepository.kt
  app/src/main/java/com/android04/godfisherman/localdatabase/dao/FeedCachedDao.kt
  app/src/main/java/com/android04/godfisherman/localdatabase/entity/FeedCached.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedFragment.kt
  app/src/main/java/com/android04/godfisherman/utils/AppGlideModule.kt
  app/src/main/java/com/android04/godfisherman/utils/FeedMapper.kt
  app/src/main/java/com/android04/godfisherman/utils/FeedUtil.kt
  app/src/main/res/values/strings.xml
Labels: 🐟피드 화면, 📸사진 업로드 화면

#92 스톱워치 화면 연결, 타임라인 데이터 업로드
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android04/godfisherman/data/datasource/stopwatchdatasource/StopwatchDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/stopwatchdatasource/local/StopwatchLocalDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/StopwatchRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchInfoFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/TestStopwatchFragment.kt
  app/src/main/java/com/android04/godfisherman/utils/StopwatchService.kt
  app/src/main/java/com/android04/godfisherman/utils/UploadDialog.kt
  app/src/main/res/drawable/bg_upload_dialog.xml
  app/src/main/res/drawable/ic_upload_dialog.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_upload.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_stopwatch.xml
  app/src/main/res/values/strings.xml
Labels: 🐟피드 화면, ⏱낚시 스톱워치 화면

#95 날씨 정보 구현, 로그인 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android04/godfisherman/data/datasource/homedatasource/HomeDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/homedatasource/remote/HomeRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/HomeRepository.kt
  app/src/main/java/com/android04/godfisherman/network/response/WeatherResponse.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeData.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/home/WeatherRecyclerViewAdapter.kt
  app/src/main/java/com/android04/godfisherman/ui/login/LogInActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/login/LogInViewModel.kt
  app/src/main/java/com/android04/godfisherman/utils/BindingAdapter.kt
  app/src/main/java/com/android04/godfisherman/utils/Util.kt
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/dialog_upload_loading.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_weather_detail.xml
  app/src/main/res/values/strings.xml
Labels: 🎪홈 화면, 로그인 화면

#97 위치권한 요청 및 위치 업데이트
  app/build.gradle
  app/src/main/java/com/android04/godfisherman/data/DTO/Gps.kt
  app/src/main/java/com/android04/godfisherman/data/repository/LocationRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainViewModel.kt
  app/src/main/java/com/android04/godfisherman/utils/LocationHelper.kt
  app/src/main/java/com/android04/godfisherman/utils/ParcelableHelper.kt
  app/src/main/java/com/android04/godfisherman/utils/SharedPreferenceManager.kt
Labels: 🎪홈 화면

#99 홈 UI 수정
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/home/RankingRecyclerViewAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_ranking.xml
  app/src/main/res/layout/item_waiting_ranking.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🎪홈 화면

#103 인트로 슬라이더 화면 설정
  app/src/main/java/com/android04/godfisherman/ui/intro/GodFishermanIntro.kt
  app/src/main/res/drawable/ic_camera.png
  app/src/main/res/drawable/ic_ranking.png
  app/src/main/res/drawable/ic_stopwatch.png
  app/src/main/res/values/colors.xml
Labels: 인트로 슬라이더 화면

#107 스와이프 문제 해결, 상태바 색상 일부 수정
  app/src/main/java/com/android04/godfisherman/ui/base/BaseFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchInfoFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/TestStopwatchFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_stopwatch.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/xml/activity_main_xml_container_scene.xml
Labels: bug, ⏱낚시 스톱워치 화면

#108 4주차 트러블 슈팅
  app/src/main/java/com/android04/godfisherman/data/repository/StopwatchRepository.kt
  app/src/main/java/com/android04/godfisherman/data/repository/UploadRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadViewModel.kt
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/layout/fragment_feed.xml
Labels: bug, 🐟피드 화면, 📸사진 업로드 화면

#109 페이징 구현
  app/build.gradle
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/FeedDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/local/FeedLocalDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/remote/FeedRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/FeedRepository.kt
  app/src/main/java/com/android04/godfisherman/localdatabase/dao/FeedCachedDao.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedAdapter.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedViewModel.kt
  app/src/main/java/com/android04/godfisherman/utils/StopwatchNotification.kt
Labels: 🐟피드 화면

#113 로그인 오류 수정, 남은 용량 계산처리, 홈 화면 새로고침
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/login/LogInActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/login/LogInViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/android04/godfisherman/utils/BindingAdapter.kt
  app/src/main/java/com/android04/godfisherman/utils/StorageManager.kt
  app/src/main/res/layout/fragment_home.xml
Labels: 🎪홈 화면, 마이페이지 화면

#110 페이징 수정, 위치정보 요청 수정
  app/src/main/java/com/android04/godfisherman/data/repository/LocationRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/utils/BindingAdapter.kt
  app/src/main/java/com/android04/godfisherman/utils/Extension.kt
  app/src/main/java/com/android04/godfisherman/utils/LocationHelper.kt
  app/src/main/res/layout/fragment_feed.xml
Labels: 🎪홈 화면, 🐟피드 화면

#111 버그 수정
  app/src/main/java/com/android04/godfisherman/common/LoadingDialogProvider.kt
  app/src/main/java/com/android04/godfisherman/data/repository/HomeRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/home/RankingDetailViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/TestStopwatchFragment.kt
  app/src/main/java/com/android04/godfisherman/utils/BindingAdapter.kt
  app/src/main/java/com/android04/godfisherman/utils/RecyclerViewEmptySupport.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: bug

#116 카메라 오류 수정, 온도 수정, 로그인 리팩토링
  app/src/main/java/com/android04/godfisherman/data/repository/HomeRepository.kt
  app/src/main/java/com/android04/godfisherman/data/repository/LogInRepository.kt
  app/src/main/java/com/android04/godfisherman/data/repository/UploadRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/home/WeatherRecyclerViewAdapter.kt
  app/src/main/java/com/android04/godfisherman/ui/login/LogInActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/login/LogInViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/mypage/UserInfo.kt
  app/src/main/java/com/android04/godfisherman/utils/FirebaseAuthManager.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: bug🐛, Refactor🔨

#114 타임라인 업로드 로딩 / 에러 처리, 버그 수정, 리팩터링
  app/src/main/java/com/android04/godfisherman/ui/main/MainActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/TestStopwatchFragment.kt
  app/src/main/java/com/android04/godfisherman/utils/BindingAdapter.kt
  app/src/main/java/com/android04/godfisherman/utils/RecyclerViewEmptySupport.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_ranking_detail.xml
  app/src/main/res/layout/fragment_stopwatch.xml
  app/src/main/res/layout/item_ranking.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
Labels: bug🐛, Refactor🔨

#115 홈 화면 메모리 캐싱 & 기타 리팩토링
  app/src/main/java/com/android04/godfisherman/common/FishRankingRequest.kt
  app/src/main/java/com/android04/godfisherman/data/cache/HomeInfoCache.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/remote/FeedRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/homedatasource/HomeDataSource.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/homedatasource/remote/HomeRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/datasource/uploadDataSource/remote/UploadRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/HomeRepository.kt
  app/src/main/java/com/android04/godfisherman/di/AppDiModule.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/home/RankingDetailViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/notifications/NotificationsFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/notifications/NotificationsViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notifications.xml
Labels: bug🐛, Refactor🔨

#121 위치 정보 요청, 스톱워치 리팩토링
  app/src/main/java/com/android04/godfisherman/data/repository/FeedRepository.kt
  app/src/main/java/com/android04/godfisherman/data/repository/LocationRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/TestStopwatchFragment.kt
  app/src/main/java/com/android04/godfisherman/utils/BindingAdapter.kt
  app/src/main/java/com/android04/godfisherman/utils/LocationHelper.kt
  app/src/main/java/com/android04/godfisherman/utils/SharedPreferenceManager.kt
  app/src/main/java/com/android04/godfisherman/utils/StopwatchManager.kt
  app/src/main/java/com/android04/godfisherman/utils/StopwatchService.kt
  app/src/main/java/com/android04/godfisherman/utils/UploadDialog.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_test_stopwatch.xml
  app/src/main/res/layout/item_time_line_in_stop_watch.xml
Labels: bug🐛, Refactor🔨

#127 피드 캐싱 관련 수정
  app/src/main/java/com/android04/godfisherman/data/datasource/feedDatasource/remote/FeedRemoteDataSourceImpl.kt
  app/src/main/java/com/android04/godfisherman/data/repository/FeedRepository.kt
  app/src/main/java/com/android04/godfisherman/di/AppDiModule.kt
  app/src/main/java/com/android04/godfisherman/di/CoroutinesDispatchersModule.kt
  app/src/main/java/com/android04/godfisherman/di/CoroutinesQualifiers.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedAdapter.kt
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedRecyclerViewAdapter.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_ranking_detail.xml
  app/src/main/res/layout/item_ranking.xml
  app/src/main/res/layout/item_time_line_in_stop_watch.xml
  app/src/main/res/layout/item_timeline.xml
  app/src/main/res/layout/item_timeline_photo.xml
  app/src/main/res/layout/item_weather_detail.xml
Labels: bug🐛, Refactor🔨

#126 메인 액티비티 모션레이아웃 관련 리팩터링, 기타 버그 수정
  app/src/main/java/com/android04/godfisherman/ui/feed/FeedAdapter.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/main/SwipeMotionLayoutWrapper.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/StopwatchInfoFragment.kt
  app/src/main/java/com/android04/godfisherman/utils/BindingAdapter.kt
  app/src/main/res/xml/activity_main_xml_container_scene.xml
Labels: bug🐛, Refactor🔨

#124 마이 페이지, 로그인, 홈 화면 리팩토링
  app/src/main/java/com/android04/godfisherman/data/repository/HomeRepository.kt
  app/src/main/java/com/android04/godfisherman/data/repository/IntroRepository.kt
  app/src/main/java/com/android04/godfisherman/data/repository/LogInRepository.kt
  app/src/main/java/com/android04/godfisherman/data/repository/UploadRepository.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/CameraViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadActivity.kt
  app/src/main/java/com/android04/godfisherman/ui/camera/upload/UploadViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/intro/IntroViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/android04/godfisherman/utils/FirebaseAuthManager.kt
  app/src/main/java/com/android04/godfisherman/utils/Util.kt
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_feed_timeline_type.xml
  app/src/main/res/values/strings.xml
Labels: bug🐛, Refactor🔨

#132 위치요청 오류 리팩토링
  app/src/main/java/com/android04/godfisherman/common/LocationHelper.kt
  app/src/main/java/com/android04/godfisherman/common/constant/Const.kt
  app/src/main/java/com/android04/godfisherman/data/repository/LocationRepository.kt
  app/src/main/java/com/android04/godfisherman/presentation/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/presentation/main/MainViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/home/HomeFragment.kt
  app/src/main/java/com/android04/godfisherman/ui/main/MainActivity.kt
  app/src/main/java/com/android04/godfisherman/utils/StopwatchManager.kt
Labels: bug🐛, Refactor🔨

#136 IO 디스패처 주입
  app/build.gradle
  app/src/main/java/com/android04/godfisherman/presentation/home/HomeViewModel.kt
  app/src/main/java/com/android04/godfisherman/presentation/main/MainViewModel.kt
  app/src/main/java/com/android04/godfisherman/presentation/rankingdetail/RankingDetailViewModel.kt
  app/src/main/java/com/android04/godfisherman/presentation/upload/UploadViewModel.kt
  app/src/main/java/com/android04/godfisherman/ui/stopwatch/ContinueDialog.kt
  build.gradle
Labels: Refactor🔨
